### ISSUE TITLE
建议加入 proxychains 命令行代理方法

### ISSUE THREAD

**Issue by CHN-STUDENT** [hedzr/mirror-list#2]
RT，
proxychains 是一个命令行代理程序。支持连接 http,https 和 sockv5为命令行进行代理。
ref:
https://github.com/rofl0r/proxychains-ng
https://wizardforcel.gitbooks.io/daxueba-kali-linux-tutorial/content/11.html

**Comment by hedzr** [comment]
这样的话，要加的其实多了。
例如 tsocks 不比 proxychains 难用，cow 等等等等。
需要评估一下

**Comment by hedzr** [comment]
close since silent state
